import { randomBytes } from "node:crypto"
import { createKeyPairSignerFromPrivateKeyBytes, isAddress, type KeyPairSigner } from "@solana/kit"
import { isSealingConfigured, readCookie, sealFor, unsealFor, type CookieWrite } from "@/lib/connections/sealed-cookie"
import { browserIdCookie, isBrowserId, newBrowserId, readBrowserId } from "@/lib/identity/browser-id"

// The agents' wallet of one browser: a Solana devnet keypair generated by the server on first
// use and kept ONLY in a sealed httpOnly cookie (AES-256-GCM, its own derived key). The browser
// holds ciphertext it cannot open; the server holds no copy. The person funds it from their own
// wallet and it pays the x402 hires their agents make. Losing the cookie loses access to what
// is left in it (devnet only); the UI says so and offers "withdraw all".

export const AGENT_WALLET_COOKIE = "ac_agent_wallet"
export const AGENT_WALLET_MAX_AGE = 365 * 24 * 60 * 60

type SealedWallet = { v: 1; uid: string; seed: string; address: string; createdAt: string }

export type AgentWalletRecord = {
  /** The browser id this wallet belongs to; caps and approvals count against it. */
  uid: string
  /** 32-byte Ed25519 private key. Server memory only. */
  seed: Uint8Array
  address: string
  createdAt: string
}

export async function createAgentWallet(uid: string, options: { random?: (size: number) => Buffer; now?: Date } = {}): Promise<AgentWalletRecord> {
  const seed = new Uint8Array((options.random ?? randomBytes)(32))
  const signer = await createKeyPairSignerFromPrivateKeyBytes(seed)
  return { uid, seed, address: signer.address, createdAt: (options.now ?? new Date()).toISOString() }
}

export function agentWalletCookie(record: AgentWalletRecord): CookieWrite {
  const payload: SealedWallet = {
    v: 1,
    uid: record.uid,
    seed: Buffer.from(record.seed).toString("base64url"),
    address: record.address,
    createdAt: record.createdAt,
  }
  return { name: AGENT_WALLET_COOKIE, value: sealFor("agent-wallet", payload), maxAge: AGENT_WALLET_MAX_AGE }
}

export function readAgentWallet(req: Request): { record: AgentWalletRecord; stale: boolean } | null {
  try {
    const opened = unsealFor<SealedWallet>("agent-wallet", readCookie(req, AGENT_WALLET_COOKIE))
    const value = opened?.value
    if (!opened || !value || value.v !== 1 || !isBrowserId(value.uid) || typeof value.address !== "string" || !isAddress(value.address)) return null
    const seed = Buffer.from(String(value.seed), "base64url")
    if (seed.length !== 32) return null
    return {
      record: { uid: value.uid, seed: new Uint8Array(seed), address: value.address, createdAt: String(value.createdAt ?? "") },
      stale: opened.stale,
    }
  } catch {
    return null
  }
}

/** The signer for a wallet record, checked against the address sealed with it. */
export async function signerFor(record: AgentWalletRecord): Promise<KeyPairSigner> {
  const signer = await createKeyPairSignerFromPrivateKeyBytes(record.seed)
  if (signer.address !== record.address) throw new Error("The agents' wallet cookie does not match its address.")
  return signer
}

export type ResolvedAgentWallet = {
  uid: string
  wallet: AgentWalletRecord | null
  /** Cookies to set on the response: a new id or wallet, or values re-sealed after a rotation. */
  cookies: CookieWrite[]
  created: boolean
}

/**
 * Who this browser is and which agents' wallet it holds. The wallet anchors the identity: when
 * both cookies exist and disagree, the wallet's id wins and the id cookie is rewritten, so the
 * caps on a wallet cannot be reset by deleting only the id cookie.
 * With `create`, a browser without a wallet gets one. Null when cookies cannot be sealed here.
 */
export async function resolveAgentWallet(req: Request, options: { create: boolean; refresh?: boolean }): Promise<ResolvedAgentWallet | null> {
  if (!isSealingConfigured()) return null
  const cookies: CookieWrite[] = []
  const existing = readAgentWallet(req)
  const browser = readBrowserId(req)

  if (existing) {
    const uid = existing.record.uid
    if (!browser || browser.id !== uid || browser.stale || options.refresh) cookies.push(browserIdCookie(uid))
    if (existing.stale || options.refresh) cookies.push(agentWalletCookie(existing.record))
    return { uid, wallet: existing.record, cookies, created: false }
  }

  const uid = browser?.id ?? newBrowserId()
  if (!browser || browser.stale || options.refresh) cookies.push(browserIdCookie(uid))
  if (!options.create) return { uid, wallet: null, cookies, created: false }
  const wallet = await createAgentWallet(uid)
  cookies.push(agentWalletCookie(wallet))
  return { uid, wallet, cookies, created: true }
}
